version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5027:80"  # Mapowanie portu 80 wewnątrz kontenera na 5000 na hoście
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapowanie portu 80 wewnątrz kontenera na 3000 na hoście (nginx)
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
